version: '3.0'

services:
  backend:
    image: pranshugupta54/backend:c4228f4
    ports:
      - "4001:4001"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ~/secrets/backend